// <auto-generated>
//   Embedded font metrics for the managed EmbeddedMetricsMeasurer: advance-per-em for a Latin
//   charset from Shantell Sans (sans) + IBM Plex Mono, plus per-em ascent/descent. Regenerate with
//   the Beck.MetricsGen console (tools/Beck.MetricsGen). Do not edit by hand.
// </auto-generated>
namespace Beck.Rendering.Text;

internal static class ShantellSansMetricsData
{
    public static readonly int[] SansWeights = { 400 };
    public static readonly double[] SansAscent = { 1.02 };
    public static readonly double[] SansDescent = { 0.32 };
    public static readonly double[] SansFallback = { 0.5355 };
    public static readonly double[][] SansAscii =
    {
        new double[] { 0.34, 0.265, 0.419, 0.921, 0.7, 0.906, 0.6, 0.259, 0.421, 0.387, 0.48, 0.7, 0.234, 0.471, 0.259, 0.33, 0.7, 0.405, 0.7, 0.7, 0.7, 0.609, 0.7, 0.689, 0.7, 0.7, 0.27, 0.27, 0.7, 0.7, 0.7, 0.462, 0.848, 0.713, 0.579, 0.605, 0.654, 0.613, 0.559, 0.735, 0.736, 0.547, 0.584, 0.634, 0.556, 0.936, 0.754, 0.716, 0.57, 0.716, 0.67, 0.549, 0.615, 0.663, 0.665, 0.948, 0.637, 0.598, 0.616, 0.492, 0.33, 0.453, 0.61, 0.7, 0.36, 0.601, 0.579, 0.498, 0.619, 0.552, 0.349, 0.599, 0.613, 0.276, 0.241, 0.548, 0.304, 0.848, 0.596, 0.591, 0.553, 0.573, 0.453, 0.485, 0.42, 0.559, 0.538, 0.857, 0.504, 0.563, 0.603, 0.512, 0.273, 0.513, 0.7 },
    };

    // (codepoint, advance-per-em per sans weight)
    public static readonly (int Cp, double[] Adv)[] SansExtra =
    {
        (0xA0, new double[] { 0.34 }),
        (0xA1, new double[] { 0.265 }),
        (0xA2, new double[] { 0.555 }),
        (0xA3, new double[] { 0.7 }),
        (0xA4, new double[] { 0.7 }),
        (0xA5, new double[] { 0.7 }),
        (0xA6, new double[] { 0.296 }),
        (0xA7, new double[] { 0.561 }),
        (0xA8, new double[] { 0.562 }),
        (0xA9, new double[] { 0.929 }),
        (0xAA, new double[] { 0.547 }),
        (0xAB, new double[] { 0.618 }),
        (0xAC, new double[] { 0.7 }),
        (0xAD, new double[] { 0 }),
        (0xAE, new double[] { 0.799 }),
        (0xAF, new double[] { 0.48 }),
        (0xB0, new double[] { 0.553 }),
        (0xB1, new double[] { 0.7 }),
        (0xB2, new double[] { 0.44 }),
        (0xB3, new double[] { 0.44 }),
        (0xB4, new double[] { 0.272 }),
        (0xB5, new double[] { 0.7 }),
        (0xB6, new double[] { 0.759 }),
        (0xB7, new double[] { 0.259 }),
        (0xB8, new double[] { 0.562 }),
        (0xB9, new double[] { 0.44 }),
        (0xBA, new double[] { 0.538 }),
        (0xBB, new double[] { 0.618 }),
        (0xBC, new double[] { 1.1 }),
        (0xBD, new double[] { 1.1 }),
        (0xBE, new double[] { 1.1 }),
        (0xBF, new double[] { 0.302 }),
        (0xC0, new double[] { 0.713 }),
        (0xC1, new double[] { 0.713 }),
        (0xC2, new double[] { 0.713 }),
        (0xC3, new double[] { 0.713 }),
        (0xC4, new double[] { 0.713 }),
        (0xC5, new double[] { 0.713 }),
        (0xC6, new double[] { 1.032 }),
        (0xC7, new double[] { 0.605 }),
        (0xC8, new double[] { 0.613 }),
        (0xC9, new double[] { 0.613 }),
        (0xCA, new double[] { 0.613 }),
        (0xCB, new double[] { 0.613 }),
        (0xCC, new double[] { 0.547 }),
        (0xCD, new double[] { 0.547 }),
        (0xCE, new double[] { 0.547 }),
        (0xCF, new double[] { 0.547 }),
        (0xD0, new double[] { 0.642 }),
        (0xD1, new double[] { 0.754 }),
        (0xD2, new double[] { 0.716 }),
        (0xD3, new double[] { 0.716 }),
        (0xD4, new double[] { 0.716 }),
        (0xD5, new double[] { 0.716 }),
        (0xD6, new double[] { 0.716 }),
        (0xD7, new double[] { 0.7 }),
        (0xD8, new double[] { 0.726 }),
        (0xD9, new double[] { 0.663 }),
        (0xDA, new double[] { 0.663 }),
        (0xDB, new double[] { 0.663 }),
        (0xDC, new double[] { 0.663 }),
        (0xDD, new double[] { 0.598 }),
        (0xDE, new double[] { 0.575 }),
        (0xDF, new double[] { 0.645 }),
        (0xE0, new double[] { 0.601 }),
        (0xE1, new double[] { 0.601 }),
        (0xE2, new double[] { 0.601 }),
        (0xE3, new double[] { 0.601 }),
        (0xE4, new double[] { 0.601 }),
        (0xE5, new double[] { 0.601 }),
        (0xE6, new double[] { 0.876 }),
        (0xE7, new double[] { 0.498 }),
        (0xE8, new double[] { 0.552 }),
        (0xE9, new double[] { 0.552 }),
        (0xEA, new double[] { 0.552 }),
        (0xEB, new double[] { 0.552 }),
        (0xEC, new double[] { 0.276 }),
        (0xED, new double[] { 0.276 }),
        (0xEE, new double[] { 0.276 }),
        (0xEF, new double[] { 0.276 }),
        (0xF0, new double[] { 0.59 }),
        (0xF1, new double[] { 0.596 }),
        (0xF2, new double[] { 0.591 }),
        (0xF3, new double[] { 0.591 }),
        (0xF4, new double[] { 0.591 }),
        (0xF5, new double[] { 0.591 }),
        (0xF6, new double[] { 0.591 }),
        (0xF7, new double[] { 0.7 }),
        (0xF8, new double[] { 0.6 }),
        (0xF9, new double[] { 0.559 }),
        (0xFA, new double[] { 0.559 }),
        (0xFB, new double[] { 0.559 }),
        (0xFC, new double[] { 0.559 }),
        (0xFD, new double[] { 0.563 }),
        (0xFE, new double[] { 0.593 }),
        (0xFF, new double[] { 0.563 }),
        (0x2013, new double[] { 0.7 }),
        (0x2014, new double[] { 1 }),
        (0x2018, new double[] { 0.212 }),
        (0x2019, new double[] { 0.212 }),
        (0x201C, new double[] { 0.471 }),
        (0x201D, new double[] { 0.48 }),
        (0x2022, new double[] { 0.5 }),
        (0x2026, new double[] { 0.841 }),
        (0x2190, new double[] { 0.7 }),
        (0x2191, new double[] { 0.7 }),
        (0x2192, new double[] { 0.7 }),
        (0x2193, new double[] { 0.7 }),
    };

    public static readonly int[] MonoWeights = { 400, 500, 700 };
    public static readonly double[] MonoAscent = { 1.025, 1.025, 1.025 };
    public static readonly double[] MonoDescent = { 0.275, 0.275, 0.275 };
    public static readonly double[] MonoAdvance = { 0.6, 0.6, 0.6 };
}
