using Beck;

// Emits Beck diagrams from code — the general "generate from any model" pattern.
// Prints raw YAML (so it can be validated/rendered). Pass an argument to pick a
// sample: architecture (default) | sequence | state | class | reflection.
var which = args.Length > 0 ? args[0] : "architecture";

if (which == "sequence")
{
    Console.WriteLine(new SequenceDiagramBuilder("Checkout")
        .Subtitle("Generated by Beck.Authoring")
        .Participant("web", "Web App", NodeKind.User)
        .Participant("api", "Orders API")
        .Participant("pay", p => p.Title("Payments").Icon("lock").Accent(AccentToken.Info))
        .Participant("db", p => p.Title("Postgres").Kind(NodeKind.Db))
        .Message("web", "api", "POST /orders")
        .Message("api", "api", "validate cart")
        .Section("Payment")
        .Message("api", "pay", "capture")
        .Reply("pay", "api", "captured")
        .Section("Persist")
        .Message("api", "db", "INSERT order")
        .Reply("db", "api", "ok")
        .Reply("api", "web", "201 Created")
        .ToYaml());
    return;
}

if (which == "state")
{
    Console.WriteLine(new StateDiagramBuilder("Order Lifecycle")
        .Direction(Direction.LR)
        .State("review", "In Review", AccentToken.Warn)
        .State("published", "Published", AccentToken.Success)
        .Initial("draft")
        .Transition("draft", "review", "submit")
        .Transition("review", "draft", "reject")
        .Transition("review", "published", "approve")
        .Final("published")
        .ToYaml());
    return;
}

if (which == "class")
{
    Console.WriteLine(new ClassDiagramBuilder("Order Model")
        .Class("entity", c => c.Name("Entity").Stereotype("abstract").Accent(AccentToken.Neutral)
            .Fields("Id: Guid", "CreatedAt: DateTimeOffset"))
        .Class("order", c => c.Name("Order").Stereotype("aggregate")
            .Fields("Status: OrderStatus", "Total: Money")
            .Methods("AddLine(sku, qty)", "Submit()"))
        .Class("line", c => c.Name("OrderLine").Fields("Sku: string", "Qty: int"))
        .Inherits("order", "entity")
        .Composition("order", "line", fromCard: "1", toCard: "*")
        .ToYaml());
    return;
}

if (which == "reflection")
{
    // The always-current-domain-model pattern: reflect real CLR types into a
    // class diagram. Any docs page can do this against its own assemblies.
    Console.WriteLine(ClassDiagramBuilder
        .FromTypes(typeof(Entity), typeof(Order), typeof(OrderLine), typeof(Customer), typeof(OrderStatus))
        .Title("Order Model (reflected)")
        .ToYaml());
    return;
}

var yaml = new DiagramBuilder("Web Platform")
    .Subtitle("Generated by Beck.Authoring")
    .Direction(Direction.TB)
    .Node("web", n => n.Title("Web App").Kind(NodeKind.User).Subtitle("Browser SPA"))
    .Node("gw", n => n.Title("API Gateway").Kind(NodeKind.Gateway).Subtitle("Routing + auth"))
    .Node("auth", "Auth Service")
    .Node("catalog", "Catalog Service")
    .Node("orders", "Orders Service")
    .Node("authdb", n => n.Title("Auth DB").Kind(NodeKind.Db))
    .Node("catalogdb", n => n.Title("Catalog DB").Kind(NodeKind.Db))
    .Node("events", n => n.Title("Events").Kind(NodeKind.Queue).Subtitle("Message bus"))
    .Group("services", g => g.Label("Services").Members("auth", "catalog", "orders").Accent(AccentToken.Primary))
    .Group("data", g => g.Label("Data Stores").Members("authdb", "catalogdb", "events").Accent(AccentToken.Info))
    .Edge("web", "gw")
    .Edge("gw", "auth")
    .Edge("gw", "catalog")
    .Edge("gw", "orders")
    .Edge("auth", "authdb")
    .Edge("catalog", "catalogdb")
    .Edge("orders", "catalogdb")
    .Edge("orders", "events", e => e.Kind(EdgeKind.Async))
    .Flow(f => f
        .Repeat(-1)
        .RepeatDelay(1.5)
        .Status("web", "GET /orders", color: "neutral")
        .Packet("web", "gw", label: "request", shape: PacketShape.Circle, impact: true)
        .Parallel(p => p
            .Packet("gw", "auth", color: "info")
            .Working("orders"))
        .Packet("gw", "orders")
        .Packet("orders", "catalogdb", color: "warn")
        .Idle("orders")
        .Packet("orders", "events", color: "success", shape: PacketShape.Ring, impact: true)
        .Wait(1))
    .ToYaml();

Console.WriteLine(yaml);

// Demo domain for the `reflection` sample.
internal abstract class Entity
{
    public Guid Id { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}

internal sealed class Order : Entity
{
    public OrderStatus Status { get; set; }
    public decimal Total { get; set; }
    public Customer? Customer { get; set; }
    public List<OrderLine> Lines { get; } = new();
    public void AddLine(string sku, int qty) => Lines.Add(new OrderLine { Sku = sku, Qty = qty });
    public void Submit() => Status = OrderStatus.Submitted;
}

internal sealed class OrderLine
{
    public string Sku { get; set; } = "";
    public int Qty { get; set; }
}

internal sealed class Customer : Entity
{
    public string Name { get; set; } = "";
    public string Email { get; set; } = "";
}

internal enum OrderStatus { Draft, Submitted, Shipped, Cancelled }

internal interface IOrderNotifier
{
    void OrderPlaced(Order order);
}
