using Beck;

// Emits a Beck diagram from code — the general "generate from any model" pattern,
// here hand-written. Prints the raw YAML (so it can be validated/rendered).
var yaml = new DiagramBuilder("Web Platform")
    .Subtitle("Generated by Beck.Authoring")
    .Direction(Direction.TB)
    .Node("web", n => n.Title("Web App").Kind(NodeKind.User).Subtitle("Browser SPA"))
    .Node("gw", n => n.Title("API Gateway").Kind(NodeKind.Gateway).Subtitle("Routing + auth"))
    .Node("auth", "Auth Service")
    .Node("catalog", "Catalog Service")
    .Node("orders", "Orders Service")
    .Node("authdb", n => n.Title("Auth DB").Kind(NodeKind.Db))
    .Node("catalogdb", n => n.Title("Catalog DB").Kind(NodeKind.Db))
    .Node("events", n => n.Title("Events").Kind(NodeKind.Queue).Subtitle("Message bus"))
    .Group("services", g => g.Label("Services").Members("auth", "catalog", "orders").Accent(AccentToken.Primary))
    .Group("data", g => g.Label("Data Stores").Members("authdb", "catalogdb", "events").Accent(AccentToken.Info))
    .Edge("web", "gw")
    .Edge("gw", "auth")
    .Edge("gw", "catalog")
    .Edge("gw", "orders")
    .Edge("auth", "authdb")
    .Edge("catalog", "catalogdb")
    .Edge("orders", "catalogdb")
    .Edge("orders", "events", e => e.Kind(EdgeKind.Async))
    .Flow(f => f
        .Repeat(-1)
        .RepeatDelay(1.5)
        .Status("web", "GET /orders", color: "neutral")
        .Packet("web", "gw", label: "request")
        .Parallel(p => p
            .Packet("gw", "auth", color: "info")
            .Working("orders"))
        .Packet("gw", "orders")
        .Packet("orders", "catalogdb", color: "warn")
        .Idle("orders")
        .Packet("orders", "events", color: "success")
        .Wait(1))
    .ToYaml();

Console.WriteLine(yaml);
