using System.Globalization;
using System.Text;
using HarfBuzzSharp;
using SkiaSharp;
using Xunit;

namespace Beck.Tests;

/// <summary>
/// Offline generator for <c>Beck.Rendering/Text/InterMetricsData.g.cs</c> — the embedded
/// per-glyph advance table the managed <c>InterMetricsMeasurer</c> reads. Measures the committed
/// Inter (sans) and IBM Plex Mono TTFs with HarfBuzz/Skia exactly the way <c>SkiaTextMeasurer</c>
/// does, then emits advance-per-em for a Latin charset per weight, plus per-em ascent/descent.
///
/// Not run in CI (writes a source file). Regenerate manually:
/// <code>BECK_GEN_METRICS=1 dotnet test --filter FullyQualifiedName~MetricsTableGenerator</code>
/// </summary>
public class MetricsTableGenerator
{
    // ASCII 32..126, then curated non-ASCII common in diagram text: Latin-1 (guillemets «» for
    // class stereotypes, accented letters, middle dot) plus a few Unicode punctuation/arrows.
    private static readonly int[] _extras =
    [
        .. Enumerable.Range(0xA0, 0x60),                 // Latin-1 supplement A0..FF
        0x2013, 0x2014,                                  // – —
        0x2018, 0x2019, 0x201C, 0x201D,                  // ' ' " "
        0x2022, 0x2026,                                  // • …
        0x2190, 0x2191, 0x2192, 0x2193,                  // ← ↑ → ↓
    ];

    private static readonly int[] _sansWeights = [400, 500, 600, 700];
    private static readonly int[] _monoWeights = [400, 500, 700];

    private static string Font(bool mono, int weight)
    {
        var dir = Path.Combine(AppContext.BaseDirectory, "fonts");
        var file = mono
            ? weight switch { 400 => "IBMPlexMono-Regular.ttf", 500 => "IBMPlexMono-Medium.ttf", _ => "IBMPlexMono-Bold.ttf" }
            : weight switch { 400 => "Inter-Regular.ttf", 500 => "Inter-Medium.ttf", 600 => "Inter-SemiBold.ttf", _ => "Inter-Bold.ttf" };
        return Path.Combine(dir, file);
    }

    [Fact]
    public void Generate()
    {
        if (Environment.GetEnvironmentVariable("BECK_GEN_METRICS") != "1")
        {
            return; // no-op unless explicitly regenerating
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Embedded font metrics for the managed InterMetricsMeasurer: advance-per-em for a Latin");
        sb.AppendLine("//   charset from Inter (sans) + IBM Plex Mono, plus per-em ascent/descent. Regenerate with the");
        sb.AppendLine("//   Beck.Tests MetricsTableGenerator (BECK_GEN_METRICS=1). Do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("namespace Beck.Rendering.Text;");
        sb.AppendLine();
        sb.AppendLine("internal static class InterMetricsData");
        sb.AppendLine("{");

        // ---- sans (per-glyph, per weight) ----
        var sansAscent = new double[_sansWeights.Length];
        var sansDescent = new double[_sansWeights.Length];
        var sansFallback = new double[_sansWeights.Length];
        var ascii = new double[_sansWeights.Length][];              // [weight][cp-32]
        var extra = new Dictionary<int, double[]>();              // cp -> [weight] (only glyphs present in the font)

        for (var wi = 0; wi < _sansWeights.Length; wi++)
        {
            using var f = Loaded.Open(Font(mono: false, _sansWeights[wi]));
            (sansAscent[wi], sansDescent[wi]) = f.VMetrics();

            ascii[wi] = new double[95];
            for (var cp = 32; cp <= 126; cp++)
            {
                ascii[wi][cp - 32] = f.Advance(cp) ?? 0;
            }

            // fallback = mean lowercase advance (a typical glyph width)
            sansFallback[wi] = Enumerable.Range('a', 26).Select(c => f.Advance(c) ?? 0).Average();

            foreach (var cp in _extras)
            {
                var adv = f.Advance(cp);
                if (adv is null)
                {
                    continue; // glyph absent → measurer falls back
                }

                if (!extra.TryGetValue(cp, out var row))
                {
                    extra[cp] = row = new double[_sansWeights.Length];
                }

                row[wi] = adv.Value;
            }
        }

        Arr(sb, "SansWeights", _sansWeights);
        DblArr(sb, "SansAscent", sansAscent);
        DblArr(sb, "SansDescent", sansDescent);
        DblArr(sb, "SansFallback", sansFallback);

        sb.AppendLine("    public static readonly double[][] SansAscii =");
        sb.AppendLine("    {");
        for (var wi = 0; wi < _sansWeights.Length; wi++)
        {
            sb.Append("        new double[] { ").Append(string.Join(", ", ascii[wi].Select(D))).AppendLine(" },");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    // (codepoint, advance-per-em per sans weight)");
        sb.AppendLine("    public static readonly (int Cp, double[] Adv)[] SansExtra =");
        sb.AppendLine("    {");
        foreach (var (cp, row) in extra.OrderBy(kv => kv.Key))
        {
            sb.Append("        (0x").Append(cp.ToString("X")).Append(", new double[] { ").Append(string.Join(", ", row.Select(D))).AppendLine(" }),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // ---- mono (monospace: one advance/em per weight) ----
        var monoAscent = new double[_monoWeights.Length];
        var monoDescent = new double[_monoWeights.Length];
        var monoAdvance = new double[_monoWeights.Length];
        for (var wi = 0; wi < _monoWeights.Length; wi++)
        {
            using var f = Loaded.Open(Font(mono: true, _monoWeights[wi]));
            (monoAscent[wi], monoDescent[wi]) = f.VMetrics();
            monoAdvance[wi] = f.Advance('x') ?? 0.6; // fixed-pitch: every glyph shares this advance
        }
        Arr(sb, "MonoWeights", _monoWeights);
        DblArr(sb, "MonoAscent", monoAscent);
        DblArr(sb, "MonoDescent", monoDescent);
        DblArr(sb, "MonoAdvance", monoAdvance);

        sb.AppendLine("}");

        var outPath = Path.GetFullPath(Path.Combine(
            AppContext.BaseDirectory, "../../../../../src/Beck/Text/InterMetricsData.g.cs"));
        File.WriteAllText(outPath, sb.ToString());
        Assert.True(File.Exists(outPath), outPath);
    }

    private static string D(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);

    private static void Arr(StringBuilder sb, string name, int[] vals) =>
        sb.Append("    public static readonly int[] ").Append(name).Append(" = { ")
          .Append(string.Join(", ", vals)).AppendLine(" };");

    private static void DblArr(StringBuilder sb, string name, double[] vals) =>
        sb.Append("    public static readonly double[] ").Append(name).Append(" = { ")
          .Append(string.Join(", ", vals.Select(D))).AppendLine(" };");

    /// <summary>A loaded face — HarfBuzz for shaping advances, Skia for vertical metrics.</summary>
    private sealed class Loaded : IDisposable
    {
        private readonly SKTypeface _typeface;
        private readonly Font _hb;
        private readonly Face _face;
        private readonly Blob _blob;
        private readonly int _upem;

        private Loaded(SKTypeface t, Font h, Face fa, Blob b, int upem)
            => (_typeface, _hb, _face, _blob, _upem) = (t, h, fa, b, upem);

        public static Loaded Open(string path)
        {
            var typeface = SKTypeface.FromFile(path) ?? throw new FileNotFoundException(path);
            var blob = Blob.FromFile(path);
            var face = new Face(blob, 0);
            var upem = face.UnitsPerEm;
            var hb = new Font(face);
            hb.SetFunctionsOpenType();
            hb.SetScale(upem, upem);
            return new Loaded(typeface, hb, face, blob, upem);
        }

        /// <summary>Advance-per-em for one codepoint, or null if the font has no glyph for it.</summary>
        public double? Advance(int codepoint)
        {
            using var buffer = new HarfBuzzSharp.Buffer();
            buffer.AddUtf16(char.ConvertFromUtf32(codepoint));
            buffer.GuessSegmentProperties();
            _hb.Shape(buffer);
            var infos = buffer.GlyphInfos;
            if (infos.Length == 0 || infos[0].Codepoint == 0)
            {
                return null; // .notdef → absent
            }

            long adv = 0;
            foreach (var p in buffer.GlyphPositions)
            {
                adv += p.XAdvance;
            }

            return adv / (double)_upem;
        }

        public (double Ascent, double Descent) VMetrics()
        {
            using var font = new SKFont(_typeface, 1f);
            font.GetFontMetrics(out var m);
            return (-m.Ascent, m.Descent); // at size 1, metrics are per-em
        }

        public void Dispose()
        {
            _hb.Dispose(); _face.Dispose(); _blob.Dispose(); _typeface.Dispose();
        }
    }
}