using System.Reflection;
using Beck;
using Pennington.Highlighting;

namespace Beck.Docs.Components.Reference;

/// <summary>A collaborator builder a method opens (its callback parameter's type).</summary>
internal sealed record ApiLink(string Name, string Id);

/// <summary>One method or constructor: signature, doc, and the builders it hands to a callback.</summary>
internal sealed record ApiMember(string SigHtml, string DocHtml, IReadOnlyList<ApiLink> Opens);

/// <summary>A run of members sharing one builder role (compose / add / set / …).</summary>
internal sealed record ApiMemberGroup(string Label, string Hint, IReadOnlyList<ApiMember> Members);

internal sealed record ApiClass(
    string Id,
    string Name,
    string BreadcrumbHtml,
    string MetaHtml,
    string SummaryHtml,
    IReadOnlyList<ApiMemberGroup> MemberGroups,
    string DiagramYaml,
    string? ExampleHtml,
    string? ExampleFile);

/// <summary>
/// The API reference page's model, generated by reflecting over the authoring builders and
/// joining them with their <c>Beck.xml</c> doc comments (via <see cref="BeckXmlDocs"/>) — the
/// page can't drift from the code. The per-class header diagram is derived from the same
/// reflection pass and rendered by Beck's own <see cref="ClassDiagramBuilder"/>.
/// </summary>
internal static class ApiCatalog
{
    /// <summary>Declaration order here is the page order.</summary>
    private static readonly Type[] Types =
    [
        typeof(DiagramBuilder), typeof(NodeBuilder), typeof(EdgeBuilder), typeof(GroupBuilder),
        typeof(FlowBuilder), typeof(SequenceDiagramBuilder), typeof(MessageBuilder),
        typeof(StateDiagramBuilder), typeof(StateBuilder), typeof(TransitionBuilder),
        typeof(ClassDiagramBuilder), typeof(ClassBuilder),
    ];

    public static IReadOnlyList<ApiClass> Classes => Model.Value;

    /// <summary>One tab per diagram type: the root builder and the collaborators it opens, with
    /// method compartments — every edge a real <c>Action&lt;T&gt;</c> collaboration labelled with
    /// the methods that open it, every card linking to its section.</summary>
    public static IReadOnlyList<(string Label, string Yaml)> OverviewTabs => Tabs.Value;

    private static readonly Lazy<IReadOnlyList<ApiClass>> Model = new(Build);

    private static readonly (Type Root, string Label)[] Families =
    [
        (typeof(DiagramBuilder), "Architecture"),
        (typeof(SequenceDiagramBuilder), "Sequence"),
        (typeof(StateDiagramBuilder), "State"),
        (typeof(ClassDiagramBuilder), "Class"),
    ];

    private static readonly Lazy<IReadOnlyList<(string Label, string Yaml)>> Tabs = new(() =>
        Families.Select(f => (f.Label, FamilyDiagram(f.Root))).ToArray());

    private static readonly Lazy<TextMateHighlighter> Highlighter =
        new(() => new TextMateHighlighter(new TextMateLanguageRegistry()));

    /// <summary>One "X configures Y via method" fact, mined from <c>Action&lt;T&gt;</c> parameters.</summary>
    private sealed record Usage(Type Owner, string Method, Type Target);

    private static IReadOnlyList<ApiClass> Build()
    {
        var usages = FindUsages();
        return Types.Select(t => BuildClass(t, usages)).ToArray();
    }

    /// <summary>One diagram family: the root card with its collaborator-opening methods, each
    /// collaborator with a peek at its own surface, edges labelled with the opening methods.</summary>
    private static string FamilyDiagram(Type root)
    {
        var uses = FindUsages().Where(u => u.Owner == root).ToList();
        var rootId = root.Name.ToLowerInvariant();

        var b = new ClassDiagramBuilder().Direction(Beck.Direction.LR).Animate(false);
        b.Class(rootId, c => c.Name(root.Name).Accent(AccentToken.Primary)
            .Link($"/api/#{rootId}").Methods(FocalMethods(root, uses)));

        foreach (var g in uses.GroupBy(u => u.Target))
        {
            // Name-only cards keep the map lean — each links to its full reference below.
            var id = g.Key.Name.ToLowerInvariant();
            b.Class(id, c => c.Name(g.Key.Name).Link($"/api/#{id}"));
            b.Association(rootId, id, EdgeLabel(g));
        }
        return b.ToYaml();
    }

    /// <summary>Every builder method whose callback parameter configures another builder in the set.</summary>
    private static List<Usage> FindUsages()
    {
        var usages = new List<Usage>();
        foreach (var owner in Types)
        {
            foreach (var method in PublicMethods(owner))
            {
                foreach (var p in method.GetParameters())
                {
                    if (p.ParameterType.IsGenericType &&
                        p.ParameterType.GetGenericTypeDefinition() == typeof(Action<>) &&
                        p.ParameterType.GetGenericArguments()[0] is { } target &&
                        Types.Contains(target) &&
                        target != owner) // FlowBuilder.Parallel(Action<FlowBuilder>) is not a collaboration
                    {
                        usages.Add(new Usage(owner, method.Name, target));
                    }
                }
            }
        }
        return usages;
    }

    private static ApiClass BuildClass(Type type, List<Usage> usages)
    {
        var id = type.Name.ToLowerInvariant();
        var usedBy = usages.Where(u => u.Target == type).ToList();
        var uses = usages.Where(u => u.Owner == type).ToList();

        // Role is decided per method name — an overload set is one concept, and e.g. the terse
        // Node(id, title) overload belongs beside its callback sibling — but each overload keeps
        // its own row on the page.
        var classified = PublicConstructors(type).Concat(PublicMethods(type))
            .GroupBy(m => (Ctor: m is ConstructorInfo, m.Name))
            .SelectMany(g =>
            {
                var role = Classify(type, g.ToList());
                return g.Select(m => (Role: role, Member: BuildMember(m)));
            })
            .ToList();

        var groups = classified
            .GroupBy(x => x.Role)
            .OrderBy(g => g.Key)
            .Select(g =>
            {
                var (label, hint) = Section(g.Key, IsRoot(type));
                return new ApiMemberGroup(label, hint, g.Select(x => x.Member).ToArray());
            })
            .ToArray();

        var example = BeckXmlDocs.ExampleCode(type);

        return new ApiClass(
            Id: id,
            Name: type.Name,
            BreadcrumbHtml: $"Beck.Authoring <span class=\"mx-1.5\">/</span> {type.Name}",
            MetaHtml: MetaLine(type, usedBy),
            SummaryHtml: BeckXmlDocs.SummaryHtml(type),
            MemberGroups: groups,
            DiagramYaml: Diagram(type, id, uses),
            ExampleHtml: example is null ? null : HighlightCSharp(example),
            ExampleFile: example is null ? null : "Program.cs");
    }

    /// <summary>
    /// The builder role a method-name group plays, in page order. Every rule is mechanical —
    /// derived from the reflected shape, never a hand-written table that could drift:
    /// <list type="bullet">
    /// <item><see cref="Role.Create"/> — constructors and static factories returning a builder.</item>
    /// <item><see cref="Role.Compose"/> — takes an <c>Action&lt;SomeBuilder&gt;</c> callback: declares
    ///   an element and opens its builder (the same collaborations the header diagram draws).</item>
    /// <item><see cref="Role.Add"/> — repeatable declarations: a <c>params</c> overload, the singular
    ///   of a <c>params</c> sibling (<c>Member</c>/<c>Members</c>), or a root-builder method outside
    ///   the meta surface shared by the diagram builders (<c>Section</c>, <c>Initial</c>, <c>Inherits</c>…).</item>
    /// <item><see cref="Role.Step"/> — FlowBuilder's timeline verbs: every call appends a step.</item>
    /// <item><see cref="Role.Set"/> — single-value options; calling again replaces the value.</item>
    /// <item><see cref="Role.Emit"/> — returns a non-builder: the terminal output methods.</item>
    /// </list>
    /// </summary>
    private enum Role { Create, Compose, Add, Step, Set, Emit }

    private static Role Classify(Type type, List<MethodBase> overloads)
    {
        if (overloads[0] is ConstructorInfo) return Role.Create;
        if (overloads[0] is MethodInfo { IsStatic: true } factory && Types.Contains(factory.ReturnType)) return Role.Create;
        if (overloads.OfType<MethodInfo>().Any(m => !Types.Contains(m.ReturnType))) return Role.Emit;
        if (overloads.SelectMany(m => m.GetParameters()).Any(p => BuilderCallbackTarget(p) is not null)) return Role.Compose;
        if (type == typeof(FlowBuilder)) return overloads[0].Name.StartsWith("Repeat", StringComparison.Ordinal) ? Role.Set : Role.Step;
        if (overloads.Any(HasParamsArray) || HasParamsPlural(type, overloads[0].Name)) return Role.Add;
        if (IsRoot(type) && !SharedRootMethodNames.Value.Contains(overloads[0].Name)) return Role.Add;
        return Role.Set;
    }

    private static (string Label, string Hint) Section(Role role, bool isRoot) => role switch
    {
        Role.Create => ("CREATE", "constructors and factories"),
        Role.Compose => ("COMPOSE", "adds an element — pass a callback to configure it with the linked builder"),
        Role.Add => ("ADD", "accumulates — one call per item"),
        Role.Step => ("TIMELINE", "each call appends one step to the animation"),
        Role.Set when isRoot => ("DOCUMENT", "top-level options — calling again replaces the value"),
        Role.Set => ("SET", "one value — calling again replaces it"),
        Role.Emit => ("OUTPUT", "terminal — emits the finished diagram"),
        _ => throw new ArgumentOutOfRangeException(nameof(role)),
    };

    private static ApiMember BuildMember(MethodBase method) => new(
        SigHtml: HighlightCSharp(SignatureFormatter.Format(method)),
        DocHtml: BeckXmlDocs.MemberDocHtml(method),
        Opens: method.GetParameters()
            .Select(BuilderCallbackTarget).OfType<Type>().Distinct()
            .Select(t => new ApiLink(t.Name, t.Name.ToLowerInvariant())).ToArray());

    /// <summary>The builder an <c>Action&lt;T&gt;</c> parameter opens, or null.</summary>
    private static Type? BuilderCallbackTarget(ParameterInfo p) =>
        p.ParameterType.IsGenericType &&
        p.ParameterType.GetGenericTypeDefinition() == typeof(Action<>) &&
        p.ParameterType.GetGenericArguments()[0] is { } target &&
        Types.Contains(target)
            ? target
            : null;

    private static bool HasParamsArray(MethodBase m) =>
        m.GetParameters().Any(p => p.GetCustomAttribute<ParamArrayAttribute>() != null);

    /// <summary>True when the method is the singular of a <c>params</c> plural on the same type
    /// (<c>Member</c>/<c>Members</c>, <c>Field</c>/<c>Fields</c>) — both accumulate.</summary>
    private static bool HasParamsPlural(Type type, string name) =>
        PublicMethods(type).Any(m => m.Name == name + "s" && HasParamsArray(m));

    /// <summary>The four diagram builders — the types that can emit a document.</summary>
    private static bool IsRoot(Type type) => type.GetMethod("ToYaml") != null;

    /// <summary>
    /// Method names shared by at least three of the four root diagram builders: mechanically,
    /// that shared surface is exactly the document-options API (<c>Title</c>, <c>Theme</c>,
    /// <c>Animate</c>…) — anything a single root adds on top declares elements instead.
    /// </summary>
    private static readonly Lazy<HashSet<string>> SharedRootMethodNames = new(() =>
        Types.Where(IsRoot)
            .SelectMany(t => PublicMethods(t).Select(m => m.Name).Distinct())
            .GroupBy(n => n)
            .Where(g => g.Count() >= 3)
            .Select(g => g.Key)
            .ToHashSet());

    /// <summary>Public ctors in declaration order. A compiler-default ctor has no doc comment and
    /// isn't part of the story (FlowBuilder is only ever handed to you via <c>Flow(f => …)</c>) — skip it.</summary>
    private static IEnumerable<MethodBase> PublicConstructors(Type type) =>
        type.GetConstructors()
            .Where(c => c.GetParameters().Length > 0 || BeckXmlDocs.MemberDocHtml(c).Length > 0)
            .OrderBy(c => c.MetadataToken);

    /// <summary>Public declared methods in declaration order, minus accessors and object overrides.</summary>
    private static IEnumerable<MethodBase> PublicMethods(Type type) =>
        type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(m => !m.IsSpecialName && m.Name != nameof(ToString))
            .OrderBy(m => m.MetadataToken);

    /// <summary>
    /// "namespace Beck · assembly Beck.dll" for the entry builders; for builders only ever
    /// reached through a callback, "configured via" the first (page-order) owner instead.
    /// When every non-output method returns the declaring type — true of the whole family —
    /// say so once here instead of on every row.
    /// </summary>
    private static string MetaLine(Type type, List<Usage> usedBy)
    {
        const string prefix = "namespace Beck <span class=\"mx-2\">·</span> ";
        var origin = usedBy.Count == 0 ? "assembly Beck.dll" : ConfiguredVia(usedBy);

        var chains = PublicMethods(type).OfType<MethodInfo>()
            .Where(m => Types.Contains(m.ReturnType))
            .All(m => m.ReturnType == type);
        var chain = chains
            ? $" <span class=\"mx-2\">·</span> methods chain → <span class=\"font-mono\">{type.Name}</span>"
            : "";
        return prefix + origin + chain;
    }

    private static string ConfiguredVia(List<Usage> usedBy)
    {
        var owner = usedBy.Select(u => u.Owner).OrderBy(t => Array.IndexOf(Types, t)).First();
        var methods = usedBy.Where(u => u.Owner == owner).Select(u => u.Method).Distinct().ToList();
        var via = $"{owner.Name}.{methods[0]}" + string.Concat(methods.Skip(1).Select(m => $" / .{m}"));
        return $"configured via <span class=\"font-mono\">{via}</span>";
    }

    /// <summary>
    /// The header card: just the focal builder with its method compartment — the family
    /// relationships live in the overview tabs, where there is horizontal room for them.
    /// </summary>
    private static string Diagram(Type type, string focalId, List<Usage> uses)
    {
        var b = new ClassDiagramBuilder().Animate(false);
        b.Class(focalId, c => c.Name(type.Name).Accent(AccentToken.Primary).Methods(FocalMethods(type, uses)));
        return b.ToYaml();
    }

    /// <summary>The focal card's methods compartment: the collaborator-configuring methods (plus
    /// <c>ToFence()</c>) for entry builders, the first few declared methods otherwise.</summary>
    private static string[] FocalMethods(Type type, List<Usage> uses)
    {
        if (uses.Count > 0)
        {
            var names = uses.Select(u => u.Method).Distinct().Select(n => $"{n}(…)").ToList();
            if (type.GetMethod("ToFence") != null) names.Add("ToFence()");
            return names.Take(5).ToArray();
        }
        return PublicMethods(type).Select(m => m.Name).Distinct().Take(6).Select(n => $"{n}(…)").ToArray();
    }

    private static string EdgeLabel(IGrouping<Type, Usage> group) =>
        string.Join(" / ", group.Select(u => u.Method).Distinct().Select(m => $"{m}()"));

    private static string HighlightCSharp(string code) => Highlighter.Value.Highlight(code, "csharp");
}
